development:
  adapter:   postgresql
  encoding:  unicode
  host:      localhost
  username:  postgres
  pool:      5
  database:  admin_demo_development

test:
  adapter:   postgresql
  encoding:  unicode
  host:      localhost
  username:  postgres
  pool:      5
  database:  admin_demo_test

production:
  adapter:   postgresql
  encoding:  unicode
  host:      localhost
  username:  postgres
  pool:      5
  database:  admin_demo_production
